fix: now ipmonitor service works, and many service had minor fix too

diff --git a/services/coturn/compose.yaml b/services/coturn/compose.yaml
--- a/services/coturn/compose.yaml
+++ b/services/coturn/compose.yaml
@@ -10,8 +10,8 @@
 # https://techssh.com/self-hosting/set-up-a-coturn-turn-server-for-matrix-synapse-voice-call/
 
 services:
-  turnserver:
-    image: "coturn/coturn"
+  coturn:
+    image: "coturn/coturn:latest" # debian-based image
     restart: unless-stopped
     secrets: # TODO: check correct uid and gid
       - source: ssl_certificate
@@ -26,11 +26,11 @@ services:
         mode: 0o440
     volumes:
       - type: bind
-        source: ../../data/ipmonitor/currentip.txt
-        target: /currentip.txt
+        source: ../../temp/ipmonitor
+        target: /mnt/ipmonitor/temp
         read_only: true
         bind:
-          create_host_path: false
+          create_host_path: true
       - type: bind
         source: ../coturn/turnserver.conf
         target: /etc/coturn/turnserver.conf.template
@@ -42,7 +42,7 @@ services:
         target: /usr/local/bin/go-envsubst
         image:
           subpath: usr/bin/envsubst
-      # We use busybox to allow the upstream image to be changed easily to alpine-based one (maybe in the future)
+      # We use busybox to allow the upstream image to be changed easily to alpine-based one
       - type: image
         source: library/busybox:stable-musl
         target: /usr/local/bin/busybox
@@ -50,15 +50,18 @@ services:
           subpath: bin/busybox
       - type: tmpfs
         target: /var/lib/coturn
-    network_mode: "host"
-    # Commented because this makes docker compose hang/freeze (maybe only in rootless mode?) because it want to portforward every port between COTURN_MIN_PORT and COTURN_MAX_PORT. so lets just use "network_mode: host"
+    # (Did not check myself!) but seems UDP port forwarding on docker is not very reliable/stable. so instead i commented these and added `network_mode: host`(`userns_mode: "host"` is required in [userns-remap](https://docs.docker.com/engine/security/userns-remap/#user-namespace-known-limitations) mode.
+    # Also it can make docker-compose hang/freeze(maybe only in rootless mode?) because it want to port forward every port between $COTURN_MIN_PORT and $COTURN_MAX_PORT
     #ports:
     #  - "${COTURN_PORT:-3478}:${COTURN_PORT:-3478}"
     #  - "${COTURN_PORT:-3478}:${COTURN_PORT:-3478}/udp"
-    #  # I commented because COTURN_PORT can be used for both SSL or raw if clients support that
-    #  #- "${COTURN_SSL_PORT:-5349}:${COTURN_SSL_PORT:-5349}"
-    #  #- "${COTURN_SSL_PORT:-5349}:${COTURN_SSL_PORT:-5349}/udp"
+    #  # maybe we should comment COTURN_SSL_PORT sections because COTURN_PORT works for both SSL and raw but depends on client support
+    #  - "${COTURN_SSL_PORT:-5349}:${COTURN_SSL_PORT:-5349}"
+    #  - "${COTURN_SSL_PORT:-5349}:${COTURN_SSL_PORT:-5349}/udp"
     #  - "${COTURN_MIN_PORT:-49152}-${COTURN_MAX_PORT:-65535}:${COTURN_MIN_PORT:-49152}-${COTURN_MAX_PORT:-65535}/udp"
+    network_mode: "host"
+    userns_mode: "host"
+    #
     env_file:
       - path: ../coturn/.env
         required: true
@@ -73,13 +76,37 @@ services:
         #    exit 0
         #}
         #trap 'term_handler' SIGTERM SIGINT
-
-        export COTURN_EXTERNAL_IP="$$(cat /currentip.txt)"
-        echo "# [INFO] set COTURN_EXTERNAL_IP to \"$$COTURN_EXTERNAL_IP\""
-
+        case "$${IPMONITOR_IS_ENABLED-}" in
+          true|True|y|yes|1)
+            IP="$$(cat /mnt/ipmonitor/temp/ipv4.txt || true)"
+            if [ -n "$$IP" ]; then
+              export COTURN_EXTERNAL_IP="$$IP"
+              echo "# [DEBUG] used ipmonitor to set \$$COTURN_EXTERNAL_IP to $$COTURN_EXTERNAL_IP"
+            else
+              echo "# [ERROR] tried to use ipmonitor service but \$$IP is empty!"
+              exit 1
+            fi
+            ;;
+          *)
+            echo "# [DEBUG] ipmonitor service is not enabled"
+            if [ -n "$$COTURN_EXTERNAL_IP" ]; then
+              echo "# [INFO] using predefined COTURN_EXTERNAL_IP to \"$$COTURN_EXTERNAL_IP\""
+            elif [ ! "${COTURN_EXTERNAL_IP:-none}" = "none" ]; then
+              export COTURN_EXTERNAL_IP="${COTURN_EXTERNAL_IP:-none}" # we used `-none` section to suppress docker-compose warning
+              echo "# [INFO] using defined COTURN_EXTERNAL_IP(in docker-compose) for \"$$COTURN_EXTERNAL_IP\""
+            elif [ ! "${PUBLIC_IP:-none}" = "none" ]; then
+              echo "# [INFO] using defined PUBLIC_IP(in docker-compose) for \"$$COTURN_EXTERNAL_IP\""
+              export COTURN_EXTERNAL_IP="${PUBLIC_IP:-none}" # we used `-none` section to suppress docker-compose warning
+            else
+              echo "# [WARNING] starting coturn without COTURN_EXTERNAL_IP"
+            fi
+            ;;
+        esac
         echo "# [INFO] Patching /etc/coturn/turnserver.conf"
-        go-envsubst -no-unset -no-empty -i "/etc/coturn/turnserver.conf.template" -o "/etc/coturn/turnserver.conf"
+        go-envsubst -i "/etc/coturn/turnserver.conf.template" -o "/etc/coturn/turnserver.conf"
         exec busybox su -s /bin/bash nobody -c "set -ex; source /usr/local/bin/docker-entrypoint.sh --log-file=/tmp/stdout"
+
+# TODO: check if this is needed
 secrets:
   ssl_certificate:
     environment: SSL_CERT
diff --git a/services/ipmonitor/compose.yaml b/services/ipmonitor/compose.yaml
--- a/services/ipmonitor/compose.yaml
+++ b/services/ipmonitor/compose.yaml
@@ -1,35 +1,84 @@
 services:
   ipmonitor:
-    image: alpine
-    entrypoint: /bin/sh
+    image: "alpine:latest"
+    restart: unless-stopped # TODO: maybe use "always"?
     volumes:
-        - type: bind
-          source: ../../data/ipmonitor
-          target: /data
-          read_only: false
-          bind:
-            create_host_path: true
+      - type: bind
+        source: ../../temp/ipmonitor
+        target: /temp
+        read_only: false
+        bind:
+          create_host_path: true
+    env_file:
+      - path: ../../.env.base
+        required: false
     environment:
       - IPMONITOR_URL=${IPMONITOR_URL}
-      - IPMONITOR_INTERVAL=${IPMONITOR_INTERVAL:-60} # seconds
+      - IPMONITOR_INTERVAL=${IPMONITOR_INTERVAL:-120} # seconds
+    # TODO: not sure if entrypoint is needed here
+    entrypoint: /bin/sh
     command:
       - -c
       - |
-        set -e
-        FILE_PATH="/data/currentip.txt"
+        set -eu
+        IPV4_FILE="/temp/ipv4.txt"
+        IPV6_FILE="/temp/ipv6.txt" # TODO: add ipv6 support
+        IS_HEALTHY_FILE="/tmp/is_healthy.txt"
+        IS_RESTARTED_FILE="/tmp/is_restarted.txt"
+        IS_RESTARTED="false"
+        IS_FIRST_TIME="false"
+        if [ -f "$$IS_HEALTHY_FILE" ]; then
+          rm "$$IS_HEALTHY_FILE"
+        fi
+        if [ -f "$$IS_RESTARTED_FILE" ]; then
+          if [ "$$(cat "$$IS_RESTARTED_FILE")" = "true" ]; then
+            echo "# [DEBUG] is_restarted is true"
+            IS_RESTARTED="true"
+          fi
+          rm "$$IS_RESTARTED_FILE"
+        fi
+
         update_ip() {
-          echo "# [DEBUG] update_ip(): started"
-          #NEW_IP=$$(curl -s --connect-timeout 5 --max-time 10 "$$IPMONITOR_URL")
-          NEW_IP=$$(wget -q -O- "$$IPMONITOR_URL")
+          local IS_FIRST_TIME="$$1"
+          #echo "# [DEBUG] update_ip(): started"
+          if [ -n "$${REAL_IP:-}" ]; then
+            echo "# [DEBUG] assuming public IP is static as REAL_IP($$REAL_IP) env is available"
+            NEW_IP="$${REAL_IP:-}"
+          elif [ -n "$${PUBLIC_IP:-}" ]; then
+            echo "# [DEBUG] assuming public IP is static as PUBLIC_IP($$PUBLIC_IP) env is available"
+            NEW_IP="$$PUBLIC_IP"
+          elif [ -n "$${IPMONITOR_URL:-}" ]; then
+            #NEW_IP=$$(curl -s --connect-timeout 5 --max-time 10 "$$IPMONITOR_URL") # curl seems unavailable in busybox
+            NEW_IP=$$(wget -q -O- "$$IPMONITOR_URL" || true)
+          else
+            echo "# [ERROR] non of obtaining public ip is available"
+            exit 1
+          fi
           if [ -n "$$NEW_IP" ]; then
-            if [ "$$(cat "$$FILE_PATH")" = "$$NEW_IP" ]; then
-              echo "# [INFO] current ip is equal to last ip"
+            # to avoid overrite when its manually changed
+            if [ ! -f "$$IS_HEALTHY_FILE" ]; then
+              echo "# [DEBUG] ipmonitor is healthy"
+              echo "true" >"$$IS_HEALTHY_FILE"
+            fi
+            if [ -f "$$IPV4_FILE" ] && [ "$$(cat "$$IPV4_FILE")" = "$$NEW_IP" ]; then
+              echo "# [INFO] current IP is equal to previous saved IP($$NEW_IP)"
             else
-              echo "# [INFO] updating last ip to: $$NEW_IP"
-              echo "$$NEW_IP" > "$$FILE_PATH"
+              echo "# [INFO] updating IP to: $$NEW_IP"
+              echo "$$NEW_IP" > "$$IPV4_FILE"
+              if [ "$$IS_FIRST_TIME" != true ]; then
+                echo "# [INFO] exiting to make the service rerun to force dependent services to be restarted"
+                exit 0
+              else
+                echo "# [DEBUG] exiting skipped because IS_FIRST_TIME=true"
+              fi
             fi
           else
-            echo "# [WARNING] Failed to fetch IP address"
+            echo "# [WARNING] Failed to fetch IP address using $$IPMONITOR_URL"
+            if [ "$$IS_FIRST_TIME" = true ]; then
+              if [ "$$IS_RESTARTED" != true ]; then
+                exit 1
+              fi
+            fi
           fi
         }
         term_handler() {
@@ -42,12 +91,19 @@ services:
             # Run sleep in background and wait on its PID.
             # This pattern allows the 'wait' command to be interrupted by signals 
             # much more reliably than a foreground 'sleep' in some shell environments.
-            update_ip
+            update_ip $$IS_FIRST_TIME
             sleep "$$IPMONITOR_INTERVAL" &
             wait $$!
             # If wait was interrupted by a signal, exit the loop
             if [ $$? -ne 0 ]; then
                 break
             fi
+            IS_FIRST_TIME="false"
         done
         echo "# [DEBUG] Script exited."
+    healthcheck:
+      test: ["CMD-SHELL", '[ "$$(cat /tmp/is_healthy.txt || true)" = "true" ] || exit 1']
+      start_period: 2s
+      interval: 2s
+      timeout: 5s
+      retries: 10
